name: postgres-example
channels:
  - defaults
dependencies:
  - postgresql
  - psycopg2
  - pip:
    - pandas
    - git+https://github.com/catherinedevlin/ipython-sql.git
    - git+https://github.com/jupyterlab/jupyterlab
    - jupyter-server-proxy


